version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/astrology
      - POSTGRES_URI=postgresql://postgres:password@postgres:5432/astrology
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=development-secret-key
      - JWT_REFRESH_SECRET=development-refresh-secret-key
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=astrology

  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=astrology
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  postgres_data:
  redis_data: